DROP TABLE LOCATION;
CREATE TABLE LOCATION 
(
    LOCATIONNO NUMBER PRIMARY KEY,
    ZONE VARCHAR2(32),
    LOCAL VARCHAR2(64)
);
DROP SEQUENCE LOCATION_SEQ;
CREATE SEQUENCE LOCATION_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
COMMIT; 


INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '강남구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '강북구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '강서구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '구로구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '관악구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '광진구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '금천구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '도봉구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '노원구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '동대문구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '동작구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '마포구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '서초구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '성동구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '성북구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '송파구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '양천구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '영등포구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '용산구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '은평구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '중구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '중랑구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '서울', '종로구');



INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '인천', '강화군');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '인천', '계양구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '인천', '남구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '인천', '남동구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '인천', '동구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '인천', '부평구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '인천', '서구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '인천', '연수구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '인천', '옹진군');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '인천', '중구');



INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '가평');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '고양');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '구리');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '광주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '김포');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '남양주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '동두천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '성남');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '안성');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '안양');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '양평');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '여주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '용인');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '의정부');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '이천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '파주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '평택');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '포천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '하남');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경기', '화성');



INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '강릉');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '고성');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '동해');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '삼척');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '속초');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '양구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '양양');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '영월');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '원주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '인제');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '정선');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '철원');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '춘천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '태백');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '평창');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '홍천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '화천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '강원', '횡성');



INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충북', '괴산');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충북', '단양');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충북', '보은');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충북', '영동');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충북', '옥천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충북', '음성');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충북', '제천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충북', '증평');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충북', '진천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충북', '청주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충북', '청원');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충북', '충주');



INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '계룡');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '공주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '금산');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '논산');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '당진');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '보령');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '부여');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '서산');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '서천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '아산');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '예산');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '천안');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '청양');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '태안');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '충남', '홍성');



INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '대전', '대덕구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '대전', '동구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '대전', '서구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '대전', '중구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '대전', '유성구');



INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '경산');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '경주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '고령');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '구미');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '군위');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '김천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '문경');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '봉화');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '상주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '성주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '안동');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '영덕');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '영양');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '영주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '영천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '예천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '울진');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '의성');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '칠곡');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '청도');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '청송');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '포항');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '울릉도');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경북', '독도');



INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '거창');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '고성');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '김해');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '마산');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '밀양');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '사천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '산청');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '양산');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '의령');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '진주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '창녕');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '창원');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '통영');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '하동');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '함암');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '함양');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '합천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '경남', '거제도');



INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '대구', '남구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '대구', '달서구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '대구', '달성구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '대구', '동구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '대구', '북구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '대구', '서구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '대구', '수성구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '대구', '중구');



INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '울산', '남구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '울산', '동구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '울산', '북구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '울산', '울주군');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '울산', '중구');



INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전북', '군산');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전북', '고창');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전북', '김제');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전북', '남원');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전북', '무주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전북', '부안');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전북', '순창');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전북', '완주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전북', '익산');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전북', '임실');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전북', '장수');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전북', '진안');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전북', '전주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전북', '정읍');



INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '강진');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '고흥');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '곡성');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '구례');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '광양');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '나주');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '담양');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '목포');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '무안');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '보성');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '순천');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '신안');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '여수');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '영광');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '영암');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '장성');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '장흥');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '함평');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '화순');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '해남');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '완도');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '전남', '진도');



INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '광주', '광산구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '광주', '남구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '광주', '동구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '광주', '북구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '광주', '서구');



INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '강서구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '금정구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '기장군');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '남구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '동구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '동래구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '북구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '부산진구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '사상구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '사하구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '서구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '수영구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '연제구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '영도구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '중구');
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '부산', '해운대구');


INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, '제주도', NULL);


COMMIT;




SELECT DISTINCT ZONE
  FROM LOCATION;


SELECT LOCAL
  FROM LOCATION
 WHERE ZONE = '서울'
 ORDER BY LOCATIONNO;





