DROP TABLE REVIEW;
DROP TABLE FREPLY;
DROP TABLE MEMBER;
DROP TABLE OWNER;
DROP TABLE OWNERINFO;
DROP TABLE STOREREG;
DROP TABLE NOTICE;
DROP TABLE FBOARD;
DROP TABLE QNABOARD;
DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE REVIEW_SEQ;
DROP SEQUENCE NOTICE_SEQ;
DROP SEQUENCE STOREREG_SEQ;
DROP SEQUENCE FBOARD_SEQ;
DROP SEQUENCE FREPLY_SEQ;
DROP SEQUENCE QNABOARD_SEQ;
CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE STOREREG_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE NOTICE_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE FBOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE FREPLY_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE QNABOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE REVIEW_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE TABLE MEMBER(
    MEMBERNO NUMBER PRIMARY KEY,
    MEMBERID VARCHAR2(32) UNIQUE ,
    MEMBERPW VARCHAR2(32),
    MEMBERNAME VARCHAR2(32),
    MEMBERADDR VARCHAR2(64),
    MEMBERTEL VARCHAR2(32),
    MEMBEREMAIL VARCHAR2(32),
    MEMBERAGE NUMBER,
    STATUS NUMBER
);
ALTER TABLE MEMBER MODIFY MEMBERID VARCHAR2(32) NOT NULL;
ALTER TABLE MEMBER MODIFY MEMBERAGE VARCHAR2(32) NOT NULL;

CREATE TABLE OWNERINFO (
    OWNERNO NUMBER PRIMARY KEY,
    OWNERNAME VARCHAR2(32),
    STORENAME VARCHAR2(32),
    OWNEREMAIL VARCHAR2(32) UNIQUE
);

CREATE TABLE OWNER(
    OWNERNO NUMBER PRIMARY KEY,
    OWNERPW VARCHAR2(32),
    OWNERTEL VARCHAR2(32),
    OWNEREMAIL VARCHAR2(32),
    OWNERNAME VARCHAR2(32),
    CONSTRAINT FK_ID FOREIGN KEY (OWNERNO) REFERENCES OWNERINFO(OWNERNO)
);


CREATE TABLE STOREREG
(
    STORENO NUMBER PRIMARY KEY,
    OWNERNAME VARCHAR2(32),
    STORENAME VARCHAR2(32) NOT NULL,
    STORETEL VARCHAR2(32) NOT NULL,
    STORECATEGORY VARCHAR2(32) NOT NULL,
    STORETIME VARCHAR2(32) NOT NULL,
    STOREADDR VARCHAR2(64) NOT NULL,
    STORECONTENT VARCHAR2(300) NOT NULL,
    STOREMENU VARCHAR2(200),
    STORESNS VARCHAR2(100),
    STOREHIT NUMBER,
    FILENAME1 VARCHAR2(64) NOT NULL,
    STORETABLE NUMBER NOT NULL
);

CREATE TABLE NOTICE(
    NO NUMBER PRIMARY KEY,
    WRITER VARCHAR2(32),
    TITLE VARCHAR2(500),
    CONTENT VARCHAR2(4000),
    POSTDATE DATE,
    LASTDATE DATE,
    HIT NUMBER
);
INSERT INTO NOTICE VALUES (NOTICE_SEQ.NEXTVAL,'ADMIN','공지사항','공지사항 게시판입니다',SYSDATE,SYSDATE,0);
CREATE TABLE FBOARD(
     NO NUMBER PRIMARY KEY,
      WRITER VARCHAR2(32),
      CONTENTTYPE VARCHAR2(50)  CHECK ( CONTENTTYPE IN ('이벤트', '홍보글') ) NULL,
      TITLE VARCHAR2(500),
      CONTENT VARCHAR2(4000),
      FILENAME1 VARCHAR2(1000),
      POSTDATE DATE,
      LASTDATE DATE,
      HIT NUMBER,
      STATUS NUMBER
);
insert into fboard values (fboard_seq.nextval, 'jaims', '이벤트', '이벤트글', '이벤트 시작합니다.', '', sysdate, sysdate, 0,0);
CREATE TABLE FREPLY(
      FNO NUMBER PRIMARY KEY,
      NO NUMBER,
      WRITER VARCHAR2(32),
      CONTENT VARCHAR2(500),
      POSTDATE DATE,
      CONSTRAINT FK_REPLY_NO FOREIGN KEY (NO) REFERENCES FBOARD(NO)
);

CREATE TABLE QNABOARD(
    NO NUMBER PRIMARY KEY,
    WRITER VARCHAR2(32),
    TITLE VARCHAR2(32),
    CONTENT VARCHAR2(300),
    POSTDATE DATE    
);

CREATE TABLE REVIEW(
    WRITER VARCHAR2(32),
    NO NUMBER PRIMARY KEY,
    SCORE NUMBER,
    CONTENT VARCHAR2(300),
    FILENAME VARCHAR2(64),
    STORENO NUMBER,
      CONSTRAINT FK_REVIEW FOREIGN KEY (STORENO) REFERENCES STOREREG(STORENO)
);

INSERT INTO STOREREG VALUES(1,'이연복','목란','010-1111-1111','중식','09:00-17:00','서울시 강남구 삼성동 165-5','중식점 목란입니다.','메뉴','sns',0,'이미지',10);
INSERT INTO STOREREG VALUES(2,'백종원','골목식당','010-2222-2222','한식','09:00-17:00','서울시 강남구 삼성동 165-6','한식점 골목식당입니다.','메뉴','sns',0,'이미지',10);
INSERT INTO REVIEW VALUES('qwer1234',REVIEW_SEQ.NEXTVAL,5,'정말맛있어요','FILENAME1',1);
INSERT INTO REVIEW VALUES('ADE',REVIEW_SEQ.NEXTVAL,5,'정말맛있어요','FILENAME1',2);

SELECT R.NO, R.WRITER,R.SCORE,R.CONTENT,R.FILENAME,S.STORENAME,S.STORECATEGORY 
FROM REVIEW R , STOREREG S  WHERE R.STORENO =S.STORENO AND R.WRITER='ABC';

SELECT * FROM REVIEW WHERE WRITER='ABC';
SELECT R.WRITER,R.SCORE,R.CONTENT,R.FILENAME,S.STORENAME,S.STORECATEGORY 
	FROM REVIEW R , STOREREG S  
	WHERE R.STORENO =S.STORENO AND S.STORENO='2';
    
SELECT R.NO ,R.WRITER,R.SCORE,R.CONTENT,R.FILENAME,S.STORENAME,S.STORECATEGORY 
					FROM REVIEW R , STOREREG S  WHERE R.STORENO =S.STORENO AND R.WRITER='qwer1234';
SELECT * FROM MEMBER;
INSERT INTO QNABOARD VALUES (QNABOARD_SEQ.NEXTVAL,'WRITER','TITLE','CONTENT',SYSDATE);
SELECT * FROM QNABOARD;