DROP TABLE MEMBER;
DROP TABLE OWNERIDF;
CREATE TABLE MEMBER(
    MEMBERNO NUMBER PRIMARY KEY,
    MEMBERID VARCHAR2(32) UNIQUE ,
    MEMBERPW VARCHAR2(32),
    MEMBERNAME VARCHAR2(32),
    MEMBERADDR VARCHAR2(64),
    MEMBERTEL VARCHAR2(32),
    MEMBEREMAIL VARCHAR2(32)

);
ALTER TABLE MEMBER MODIFY MEMBERID VARCHAR2(32) NOT NULL;

CREATE TABLE OWNERIDF (
    OWNERNO NUMBER PRIMARY KEY,
    OWNERNAME VARCHAR2(32),
    STORENAME VARCHAR2(32),
    OWNEREMAIL VARCHAR2(32) UNIQUE,
    STOREADDR VARCHAR2(64)
);
CREATE TABLE OWNER(
    ONWERNO NUMBER,
    OWNERPW VARCHAR2(32),
    OWNERTEL VARCHAR2(32),
    
    CONSTRAINT FK_ID FOREIGN KEY (OWNERNO) REFERENCES OWNERIDF(OWNERNO)
)

