DROP TABLE RESERVATION;
CREATE TABLE RESERVATION
(
	RESNO NUMBER PRIMARY KEY,		-- 예약번호
	STORENO NUMBER,					-- 가게번호(외래키)
	RESDATE VARCHAR2(10) NOT NULL,	-- 예약한 해당 날짜
	RESHOURS VARCHAR2(20),			-- 예약 시간
	RESPEOPLE VARCHAR2(10),			-- 예약 인원
	RESNOTE VARCHAR2(4000),			-- 예약 요청사항
	RESPOSTDATE DATE,				-- 예약한 날짜
	CONSTRAINT FK_RESERVATION_STOREREG FOREIGN KEY (STORENO) REFERENCES STOREREG(STORENO)
);


DROP SEQUENCE STORERES_SEQ;
CREATE SEQUENCE STORERES_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

INSERT INTO RESERVATION VALUES(STORERES_SEQ.NEXTVAL, 1, '2020-08-08', '10시', '3명', '요청사항입니다.', SYSDATE);
SELECT * FROM RESERVATION;