DROP TABLE STOREREG;
CREATE TABLE STOREREG
(
    STORENO NUMBER PRIMARY KEY,
    STORENAME VARCHAR2(32) NOT NULL,
    STORETEL VARCHAR2(32) NOT NULL,
    STORETIME VARCHAR2(32) NOT NULL,
    STOREADDR VARCHAR2(64) NOT NULL,
    STORECONTENT VARCHAR2(300) NOT NULL,
    STOREHIT NUMBER,
    STORETABLE NUMBER NOT NULL
);

SELECT * FROM STOREREG;

INSERT INTO STOREREG VALUES(STOREREG_SEQ.NEXTVAL, '가게2', '2222-2222', '2', '2', '가게2입니다.', 0, '2')

DROP SEQUENCE STOREREG_SEQ;
CREATE SEQUENCE STOREREG_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
